# .prettierrc.yaml
semi: true
singleQuote: false
trailingComma: none
arrowParens: avoid
useTabs: false
tabWidth: 2
bracketSameLine: true
jsxSingleQuote: true
bracketSpacing: true
quoteProps: as-needed
printWidth: 80
overrides:
  - files:
      - "*yaml"
      - "*yml"
    options:
      singleQuote: false
  - files:
      - "*css"
      - "*module.css"
    options:
      printWidth: 60
