extends:
  - stylelint-config-recommended
rules:
  at-rule-whitelist:
    - "tailwind"
    - "extends"
    - "import"
    - "keyframes"
    - "variants"
    - "responsive"
    - "layer"
    - "screen"
    - "media"
    - "apply"
    - "supports"
    - "font-face"
    - "webkit-keyframes"
    - "@apply"
    - "@tailwind"
    - "@layer"
  at-rule-no-unknown: null
  at-rule-allowed-list:
    - "tailwind"
    - "webkit-keyframes"
    - "keyframes"
    - "import"
    - "media"
    - "layer"
    - "responsive"
    - "apply"
    - "screen"
    - "extends"
    - "font-face"
    - "@apply"
    - "@tailwind"
    - "@layer"
    - "supports"
  block-no-empty: null
  named-grid-areas-no-invalid: null
  unit-whitelist:
    - em
    - rem
    - s
    - px
    - "%"
    - vw
    - vh
    - deg
    - ms
    - fr
    - vmin
    - vmax
    - vm
  at-rule-empty-line-before: null
  no-descending-specificity: null
  color-no-invalid-hex: true
  comment-no-empty: true
  declaration-block-no-duplicate-custom-properties: true
  declaration-block-no-duplicate-properties:
    - true
    - ignore:
        - consecutive-duplicates-with-different-values
  declaration-block-no-shorthand-property-overrides: true
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-invalid:
    - true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  keyframe-declaration-no-important: true
  media-feature-name-no-unknown: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-invalid-position-at-import-rule: true
  no-irregular-whitespace: true
  property-no-unknown: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
  string-no-newline: true
  unit-no-unknown: true
