/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import type * as Prisma from "./../../../node_modules/.prisma/client/index";
import type { Context as ctx } from "./../Context/index";
import type { core, connectionPluginCore } from "nexus";
import type { QueryComplexity } from "nexus/dist/plugins/queryComplexityPlugin";
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    UserScalarFieldsEnum<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "UserScalarFieldsEnum";
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    Date<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "Date";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    DateTime<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "DateTime";
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    Json<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "Json";
    /**
     * A field whose value conforms to the standard E.164 format as specified in: https://en.wikipedia.org/wiki/E.164. Basically this is +17895551234.
     */
    PhoneNumber<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "PhoneNumber";
    /**
     * A time string at UTC, such as 10:15:30Z, compliant with the `full-time` format outlined in section 5.6 of the RFC 3339profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    Time<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "Time";
    /**
     * The `Upload` scalar type represents a file upload.
     */
    Upload<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "Upload";
    /**
     * A field whose value is a generic Universally Unique Identifier: https://en.wikipedia.org/wiki/Universally_unique_identifier.
     */
    UUID<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "UUID";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    UserScalarFieldsEnum<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "UserScalarFieldsEnum";
    /**
     * A date string, such as 2007-12-03, compliant with the `full-date` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    Date<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "Date";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    DateTime<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "DateTime";
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    Json<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "Json";
    /**
     * A field whose value conforms to the standard E.164 format as specified in: https://en.wikipedia.org/wiki/E.164. Basically this is +17895551234.
     */
    PhoneNumber<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "PhoneNumber";
    /**
     * A time string at UTC, such as 10:15:30Z, compliant with the `full-time` format outlined in section 5.6 of the RFC 3339profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    Time<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "Time";
    /**
     * The `Upload` scalar type represents a file upload.
     */
    Upload<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "Upload";
    /**
     * A field whose value is a generic Universally Unique Identifier: https://en.wikipedia.org/wiki/Universally_unique_identifier.
     */
    UUID<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "UUID";
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<
        TypeName,
        FieldName
      > & {
        totalCount?: connectionPluginCore.ConnectionFieldResolver<
          TypeName,
          FieldName,
          "totalCount"
        >;
      }
    ): void;
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AccountListRelationFilter: {
    // input type
    every?: NexusGenInputs["AccountWhereInput"] | null; // AccountWhereInput
    none?: NexusGenInputs["AccountWhereInput"] | null; // AccountWhereInput
    some?: NexusGenInputs["AccountWhereInput"] | null; // AccountWhereInput
  };
  AccountOrderBy: {
    // input type
    provider?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    providerAccountId?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  AccountOrderByRelationAggregateInput: {
    // input type
    _count?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  AccountWhereInput: {
    // input type
    AND?: NexusGenInputs["AccountWhereInput"][] | null; // [AccountWhereInput!]
    NOT?: NexusGenInputs["AccountWhereInput"][] | null; // [AccountWhereInput!]
    OR?: NexusGenInputs["AccountWhereInput"][] | null; // [AccountWhereInput!]
    access_token?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    expires_at?: NexusGenInputs["IntNullableFilter"] | null; // IntNullableFilter
    id?: NexusGenInputs["StringFilter"] | null; // StringFilter
    id_token?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    oauth_token?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    oauth_token_secret?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    provider?: NexusGenInputs["StringFilter"] | null; // StringFilter
    providerAccountId?: NexusGenInputs["StringFilter"] | null; // StringFilter
    refresh_token?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    scope?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    session_state?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    token_type?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    type?: NexusGenInputs["StringFilter"] | null; // StringFilter
    user?: NexusGenInputs["UserRelationFilter"] | null; // UserRelationFilter
    userId?: NexusGenInputs["StringFilter"] | null; // StringFilter
  };
  BioListRelationFilter: {
    // input type
    every?: NexusGenInputs["BioWhereInput"] | null; // BioWhereInput
    none?: NexusGenInputs["BioWhereInput"] | null; // BioWhereInput
    some?: NexusGenInputs["BioWhereInput"] | null; // BioWhereInput
  };
  BioRelationFilter: {
    // input type
    is?: NexusGenInputs["BioWhereInput"] | null; // BioWhereInput
    isNot?: NexusGenInputs["BioWhereInput"] | null; // BioWhereInput
  };
  BioWhereInput: {
    // input type
    AND?: NexusGenInputs["BioWhereInput"][] | null; // [BioWhereInput!]
    NOT?: NexusGenInputs["BioWhereInput"][] | null; // [BioWhereInput!]
    OR?: NexusGenInputs["BioWhereInput"][] | null; // [BioWhereInput!]
    body?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    createdAt?: NexusGenInputs["DateTimeFilter"] | null; // DateTimeFilter
    headline?: NexusGenInputs["StringFilter"] | null; // StringFilter
    intro?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    status?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    updatedAt?: NexusGenInputs["DateTimeNullableFilter"] | null; // DateTimeNullableFilter
  };
  BoolFilter: {
    // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs["NestedBoolFilter"] | null; // NestedBoolFilter
  };
  CommentListRelationFilter: {
    // input type
    every?: NexusGenInputs["CommentWhereInput"] | null; // CommentWhereInput
    none?: NexusGenInputs["CommentWhereInput"] | null; // CommentWhereInput
    some?: NexusGenInputs["CommentWhereInput"] | null; // CommentWhereInput
  };
  CommentOrderByRelationAggregateInput: {
    // input type
    _count?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  CommentWhereInput: {
    // input type
    AND?: NexusGenInputs["CommentWhereInput"][] | null; // [CommentWhereInput!]
    NOT?: NexusGenInputs["CommentWhereInput"][] | null; // [CommentWhereInput!]
    OR?: NexusGenInputs["CommentWhereInput"][] | null; // [CommentWhereInput!]
    attachment?: NexusGenInputs["MediaItemRelationFilter"] | null; // MediaItemRelationFilter
    author?: NexusGenInputs["UserRelationFilter"] | null; // UserRelationFilter
    authorId?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    body?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    createdAt?: NexusGenInputs["DateTimeFilter"] | null; // DateTimeFilter
    entry?: NexusGenInputs["EntryRelationFilter"] | null; // EntryRelationFilter
    entryId?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    id?: NexusGenInputs["StringFilter"] | null; // StringFilter
    position?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    reactions?: NexusGenInputs["EnumCommentReactionsNullableListFilter"] | null; // EnumCommentReactionsNullableListFilter
    updatedAt?: NexusGenInputs["DateTimeNullableFilter"] | null; // DateTimeNullableFilter
  };
  DateTimeFilter: {
    // input type
    equals?: NexusGenScalars["DateTime"] | null; // DateTime
    gt?: NexusGenScalars["DateTime"] | null; // DateTime
    gte?: NexusGenScalars["DateTime"] | null; // DateTime
    in?: NexusGenScalars["DateTime"][] | null; // [DateTime!]
    lt?: NexusGenScalars["DateTime"] | null; // DateTime
    lte?: NexusGenScalars["DateTime"] | null; // DateTime
    not?: NexusGenInputs["NestedDateTimeFilter"] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars["DateTime"][] | null; // [DateTime!]
  };
  DateTimeNullableFilter: {
    // input type
    equals?: NexusGenScalars["DateTime"] | null; // DateTime
    gt?: NexusGenScalars["DateTime"] | null; // DateTime
    gte?: NexusGenScalars["DateTime"] | null; // DateTime
    in?: NexusGenScalars["DateTime"][] | null; // [DateTime!]
    lt?: NexusGenScalars["DateTime"] | null; // DateTime
    lte?: NexusGenScalars["DateTime"] | null; // DateTime
    not?: NexusGenInputs["NestedDateTimeNullableFilter"] | null; // NestedDateTimeNullableFilter
    notIn?: NexusGenScalars["DateTime"][] | null; // [DateTime!]
  };
  EntryListRelationFilter: {
    // input type
    every?: NexusGenInputs["EntryWhereInput"] | null; // EntryWhereInput
    none?: NexusGenInputs["EntryWhereInput"] | null; // EntryWhereInput
    some?: NexusGenInputs["EntryWhereInput"] | null; // EntryWhereInput
  };
  EntryOrderBy: {
    // input type
    createdAt?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    title?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    updatedAt?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  EntryOrderByRelationAggregateInput: {
    // input type
    _count?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  EntryRelationFilter: {
    // input type
    is?: NexusGenInputs["EntryWhereInput"] | null; // EntryWhereInput
    isNot?: NexusGenInputs["EntryWhereInput"] | null; // EntryWhereInput
  };
  EntryWhereInput: {
    // input type
    AND?: NexusGenInputs["EntryWhereInput"][] | null; // [EntryWhereInput!]
    NOT?: NexusGenInputs["EntryWhereInput"][] | null; // [EntryWhereInput!]
    OR?: NexusGenInputs["EntryWhereInput"][] | null; // [EntryWhereInput!]
    attachments?: NexusGenInputs["MediaItemListRelationFilter"] | null; // MediaItemListRelationFilter
    author?: NexusGenInputs["UserRelationFilter"] | null; // UserRelationFilter
    authorId?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    categoryId?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    comments?: NexusGenInputs["CommentListRelationFilter"] | null; // CommentListRelationFilter
    content?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    createdAt?: NexusGenInputs["DateTimeFilter"] | null; // DateTimeFilter
    featuredImage?: NexusGenInputs["MediaItemRelationFilter"] | null; // MediaItemRelationFilter
    id?: NexusGenInputs["StringFilter"] | null; // StringFilter
    published?: NexusGenInputs["BoolFilter"] | null; // BoolFilter
    title?: NexusGenInputs["StringFilter"] | null; // StringFilter
    updatedAt?: NexusGenInputs["DateTimeNullableFilter"] | null; // DateTimeNullableFilter
  };
  EnumCommentReactionsNullableListFilter: {
    // input type
    equals?: NexusGenEnums["Reaction"][] | null; // [Reaction!]
    has?: NexusGenEnums["Reaction"] | null; // Reaction
    hasEvery?: NexusGenEnums["Reaction"][] | null; // [Reaction!]
    hasSome?: NexusGenEnums["Reaction"][] | null; // [Reaction!]
    isEmpty?: boolean | null; // Boolean
  };
  EnumGenderNullableFilter: {
    // input type
    equals?: NexusGenEnums["Gender"] | null; // Gender
    in?: NexusGenEnums["Gender"][] | null; // [Gender!]
    not?: NexusGenInputs["NestedEnumGenderNullableFilter"] | null; // NestedEnumGenderNullableFilter
    notIn?: NexusGenEnums["Gender"][] | null; // [Gender!]
  };
  EnumMediaItemDestinationNullableFilter: {
    // input type
    equals?: NexusGenEnums["MediaItemDestination"] | null; // MediaItemDestination
    in?: NexusGenEnums["MediaItemDestination"][] | null; // [MediaItemDestination!]
    not?: NexusGenInputs["NestedEnumMediaItemDestinationNullableFilter"] | null; // NestedEnumMediaItemDestinationNullableFilter
    notIn?: NexusGenEnums["MediaItemDestination"][] | null; // [MediaItemDestination!]
  };
  EnumMimeTypeNullableFilter: {
    // input type
    equals?: NexusGenEnums["MimeType"] | null; // MimeType
    in?: NexusGenEnums["MimeType"][] | null; // [MimeType!]
    not?: NexusGenInputs["NestedEnumMimeTypeNullableFilter"] | null; // NestedEnumMimeTypeNullableFilter
    notIn?: NexusGenEnums["MimeType"][] | null; // [MimeType!]
  };
  EnumPronounsNullableFilter: {
    // input type
    equals?: NexusGenEnums["Pronouns"] | null; // Pronouns
    in?: NexusGenEnums["Pronouns"][] | null; // [Pronouns!]
    not?: NexusGenInputs["NestedEnumPronounsNullableFilter"] | null; // NestedEnumPronounsNullableFilter
    notIn?: NexusGenEnums["Pronouns"][] | null; // [Pronouns!]
  };
  EnumRoleNullableFilter: {
    // input type
    equals?: NexusGenEnums["Role"] | null; // Role
    in?: NexusGenEnums["Role"][] | null; // [Role!]
    not?: NexusGenInputs["NestedEnumRoleNullableFilter"] | null; // NestedEnumRoleNullableFilter
    notIn?: NexusGenEnums["Role"][] | null; // [Role!]
  };
  EnumUserStatusNullableFilter: {
    // input type
    equals?: NexusGenEnums["UserStatus"] | null; // UserStatus
    in?: NexusGenEnums["UserStatus"][] | null; // [UserStatus!]
    not?: NexusGenInputs["NestedEnumUserStatusNullableFilter"] | null; // NestedEnumUserStatusNullableFilter
    notIn?: NexusGenEnums["UserStatus"][] | null; // [UserStatus!]
  };
  FindManyUsersPaginatedInput: {
    // input type
    cursor?: NexusGenInputs["UserWhereUniqueInput"] | null; // UserWhereUniqueInput
    distinct?: NexusGenEnums["UserScalarFieldsEnum"][] | null; // [UserScalarFieldsEnum!]
    orderBy: NexusGenInputs["UserOrderByWithRelationAndSearchRelevanceInput"][]; // [UserOrderByWithRelationAndSearchRelevanceInput!]!
    pagination: NexusGenInputs["PaginationArgsInput"] | null; // PaginationArgsInput
    skip?: number | null; // Int
    take?: number | null; // Int
    where?: NexusGenInputs["UserWhereInput"] | null; // UserWhereInput
  };
  FloatNullableFilter: {
    // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: number[] | null; // [Float!]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs["NestedFloatNullableFilter"] | null; // NestedFloatNullableFilter
    notIn?: number[] | null; // [Float!]
  };
  IntNullableFilter: {
    // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs["NestedIntNullableFilter"] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  };
  MediaItemInput: {
    // input type
    ariaLabel?: string | null; // String
    caption?: string | null; // String
    description?: string | null; // String
    destination?: NexusGenEnums["MediaItemDestination"] | null; // MediaItemDestination
    fileLastModified?: NexusGenScalars["DateTime"] | null; // DateTime
    filename?: string | null; // String
    filetype?: NexusGenEnums["MimeType"] | null; // MimeType
    height?: number | null; // Float
    id?: string | null; // String
    quality?: number | null; // Int
    size?: string | null; // String
    src?: string | null; // String
    srcSet?: string | null; // String
    title?: string | null; // String
    updatedAt?: NexusGenScalars["DateTime"] | null; // DateTime
    uploadedAt?: NexusGenScalars["DateTime"] | null; // DateTime
    width?: number | null; // Float
  };
  MediaItemListRelationFilter: {
    // input type
    every?: NexusGenInputs["MediaItemWhereInput"] | null; // MediaItemWhereInput
    none?: NexusGenInputs["MediaItemWhereInput"] | null; // MediaItemWhereInput
    some?: NexusGenInputs["MediaItemWhereInput"] | null; // MediaItemWhereInput
  };
  MediaItemRelationFilter: {
    // input type
    is?: NexusGenInputs["MediaItemWhereInput"] | null; // MediaItemWhereInput
    isNot?: NexusGenInputs["MediaItemWhereInput"] | null; // MediaItemWhereInput
  };
  MediaItemWhereInput: {
    // input type
    AND?: NexusGenInputs["MediaItemWhereInput"][] | null; // [MediaItemWhereInput!]
    NOT?: NexusGenInputs["MediaItemWhereInput"][] | null; // [MediaItemWhereInput!]
    OR?: NexusGenInputs["MediaItemWhereInput"][] | null; // [MediaItemWhereInput!]
    ariaLabel?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    caption?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    description?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    destination?:
      | NexusGenInputs["EnumMediaItemDestinationNullableFilter"]
      | null; // EnumMediaItemDestinationNullableFilter
    fileLastModified?: NexusGenInputs["DateTimeNullableFilter"] | null; // DateTimeNullableFilter
    filename?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    filetype?: NexusGenInputs["EnumMimeTypeNullableFilter"] | null; // EnumMimeTypeNullableFilter
    height?: NexusGenInputs["FloatNullableFilter"] | null; // FloatNullableFilter
    id?: NexusGenInputs["StringFilter"] | null; // StringFilter
    quality?: NexusGenInputs["IntNullableFilter"] | null; // IntNullableFilter
    size?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    src?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    srcSet?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    title?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    updatedAt?: NexusGenInputs["DateTimeNullableFilter"] | null; // DateTimeNullableFilter
    uploadedAt?: NexusGenInputs["DateTimeFilter"] | null; // DateTimeFilter
    user?: NexusGenInputs["UserRelationFilter"] | null; // UserRelationFilter
    userId?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    width?: NexusGenInputs["FloatNullableFilter"] | null; // FloatNullableFilter
  };
  NestedBoolFilter: {
    // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs["NestedBoolFilter"] | null; // NestedBoolFilter
  };
  NestedDateTimeFilter: {
    // input type
    equals?: NexusGenScalars["DateTime"] | null; // DateTime
    gt?: NexusGenScalars["DateTime"] | null; // DateTime
    gte?: NexusGenScalars["DateTime"] | null; // DateTime
    in?: NexusGenScalars["DateTime"][] | null; // [DateTime!]
    lt?: NexusGenScalars["DateTime"] | null; // DateTime
    lte?: NexusGenScalars["DateTime"] | null; // DateTime
    not?: NexusGenInputs["NestedDateTimeFilter"] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars["DateTime"][] | null; // [DateTime!]
  };
  NestedDateTimeNullableFilter: {
    // input type
    equals?: NexusGenScalars["DateTime"] | null; // DateTime
    gt?: NexusGenScalars["DateTime"] | null; // DateTime
    gte?: NexusGenScalars["DateTime"] | null; // DateTime
    in?: NexusGenScalars["DateTime"][] | null; // [DateTime!]
    lt?: NexusGenScalars["DateTime"] | null; // DateTime
    lte?: NexusGenScalars["DateTime"] | null; // DateTime
    not?: NexusGenInputs["NestedDateTimeNullableFilter"] | null; // NestedDateTimeNullableFilter
    notIn?: NexusGenScalars["DateTime"][] | null; // [DateTime!]
  };
  NestedEnumGenderNullableFilter: {
    // input type
    equals?: NexusGenEnums["Gender"] | null; // Gender
    in?: NexusGenEnums["Gender"][] | null; // [Gender!]
    not?: NexusGenInputs["NestedEnumGenderNullableFilter"] | null; // NestedEnumGenderNullableFilter
    notIn?: NexusGenEnums["Gender"][] | null; // [Gender!]
  };
  NestedEnumMediaItemDestinationNullableFilter: {
    // input type
    equals?: NexusGenEnums["MediaItemDestination"] | null; // MediaItemDestination
    in?: NexusGenEnums["MediaItemDestination"][] | null; // [MediaItemDestination!]
    not?: NexusGenInputs["NestedEnumMediaItemDestinationNullableFilter"] | null; // NestedEnumMediaItemDestinationNullableFilter
    notIn?: NexusGenEnums["MediaItemDestination"][] | null; // [MediaItemDestination!]
  };
  NestedEnumMimeTypeNullableFilter: {
    // input type
    equals?: NexusGenEnums["MimeType"] | null; // MimeType
    in?: NexusGenEnums["MimeType"][] | null; // [MimeType!]
    not?: NexusGenInputs["NestedEnumMimeTypeNullableFilter"] | null; // NestedEnumMimeTypeNullableFilter
    notIn?: NexusGenEnums["MimeType"][] | null; // [MimeType!]
  };
  NestedEnumPronounsNullableFilter: {
    // input type
    equals?: NexusGenEnums["Pronouns"] | null; // Pronouns
    in?: NexusGenEnums["Pronouns"][] | null; // [Pronouns!]
    not?: NexusGenInputs["NestedEnumPronounsNullableFilter"] | null; // NestedEnumPronounsNullableFilter
    notIn?: NexusGenEnums["Pronouns"][] | null; // [Pronouns!]
  };
  NestedEnumRoleNullableFilter: {
    // input type
    equals?: NexusGenEnums["Role"] | null; // Role
    in?: NexusGenEnums["Role"][] | null; // [Role!]
    not?: NexusGenInputs["NestedEnumRoleNullableFilter"] | null; // NestedEnumRoleNullableFilter
    notIn?: NexusGenEnums["Role"][] | null; // [Role!]
  };
  NestedEnumUserStatusNullableFilter: {
    // input type
    equals?: NexusGenEnums["UserStatus"] | null; // UserStatus
    in?: NexusGenEnums["UserStatus"][] | null; // [UserStatus!]
    not?: NexusGenInputs["NestedEnumUserStatusNullableFilter"] | null; // NestedEnumUserStatusNullableFilter
    notIn?: NexusGenEnums["UserStatus"][] | null; // [UserStatus!]
  };
  NestedFloatNullableFilter: {
    // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: number[] | null; // [Float!]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs["NestedFloatNullableFilter"] | null; // NestedFloatNullableFilter
    notIn?: number[] | null; // [Float!]
  };
  NestedIntNullableFilter: {
    // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs["NestedIntNullableFilter"] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  };
  NestedStringFilter: {
    // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs["NestedStringFilter"] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    search?: string | null; // String
    startsWith?: string | null; // String
  };
  NestedStringNullableFilter: {
    // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs["NestedStringNullableFilter"] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    search?: string | null; // String
    startsWith?: string | null; // String
  };
  PaginationArgsInput: {
    // input type
    after?: string | null; // String
    before?: string | null; // String
    first: number | null; // Int
    last?: number | null; // Int
  };
  ProfileOrderBy: {
    // input type
    memberSince?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  ProfileOrderByRelevanceInput: {
    // input type
    fields: NexusGenEnums["ProfileOrderByRelevanceFieldEnum"][]; // [ProfileOrderByRelevanceFieldEnum!]!
    search: string; // String!
    sort: NexusGenEnums["SortOrderEnum"]; // SortOrderEnum!
  };
  ProfileOrderByWithRelationAndSearchRelevanceInput: {
    // input type
    _relevance?: NexusGenInputs["ProfileOrderByRelevanceInput"] | null; // ProfileOrderByRelevanceInput
    activiyFeed?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    bio?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    city?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    country?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    coverPhoto?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    dob?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    gender?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    id: NexusGenEnums["SortOrderEnum"]; // SortOrderEnum!
    lastSeen?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    memberSince?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    occupation?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    phoneNumber?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    pronouns?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    recentActivity?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    user?:
      | NexusGenInputs["UserOrderByWithRelationAndSearchRelevanceInput"]
      | null; // UserOrderByWithRelationAndSearchRelevanceInput
    userId?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  ProfileOrderByWithRelationInput: {
    // input type
    activityFeed?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    city?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    country?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    dob?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    gender?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    id?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    lastSeen?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    memberSince?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    occupation?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    phoneNumber?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    pronouns?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    recentActivity?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    user?: NexusGenInputs["UserOrderByWithRelationInput"] | null; // UserOrderByWithRelationInput
    userId?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  ProfileRelationFilter: {
    // input type
    is?: NexusGenInputs["ProfileWhereInput"] | null; // ProfileWhereInput
    isNot?: NexusGenInputs["ProfileWhereInput"] | null; // ProfileWhereInput
  };
  ProfileWhereInput: {
    // input type
    AND?: NexusGenInputs["ProfileWhereInput"][] | null; // [ProfileWhereInput!]
    NOT?: NexusGenInputs["ProfileWhereInput"][] | null; // [ProfileWhereInput!]
    OR?: NexusGenInputs["ProfileWhereInput"][] | null; // [ProfileWhereInput!]
    activiyFeed?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    bio?: NexusGenInputs["BioRelationFilter"] | null; // BioRelationFilter
    city?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    country?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    coverPhoto?: NexusGenInputs["MediaItemRelationFilter"] | null; // MediaItemRelationFilter
    dob?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    gender?: NexusGenInputs["EnumGenderNullableFilter"] | null; // EnumGenderNullableFilter
    id?: NexusGenInputs["StringFilter"] | null; // StringFilter
    lastSeen?: NexusGenInputs["DateTimeNullableFilter"] | null; // DateTimeNullableFilter
    memberSince?: NexusGenInputs["DateTimeFilter"] | null; // DateTimeFilter
    occupation?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    phoneNumber?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    pronouns?: NexusGenInputs["EnumPronounsNullableFilter"] | null; // EnumPronounsNullableFilter
    recentActivity?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    user?: NexusGenInputs["UserRelationFilter"] | null; // UserRelationFilter
    userId?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
  };
  SessionListRelationFilter: {
    // input type
    every?: NexusGenInputs["SessionWhereInput"] | null; // SessionWhereInput
    none?: NexusGenInputs["SessionWhereInput"] | null; // SessionWhereInput
    some?: NexusGenInputs["SessionWhereInput"] | null; // SessionWhereInput
  };
  SessionOrderBy: {
    // input type
    expires?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    id?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    sessionToken?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    userId?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  SessionOrderByRelationAggregateInput: {
    // input type
    _count?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  SessionOrderByWithRelationshipInput: {
    // input type
    expires?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    id?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    sessionToken?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    userId?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  SessionWhereInput: {
    // input type
    AND?: NexusGenInputs["SessionWhereInput"][] | null; // [SessionWhereInput!]
    NOT?: NexusGenInputs["SessionWhereInput"][] | null; // [SessionWhereInput!]
    OR?: NexusGenInputs["SessionWhereInput"][] | null; // [SessionWhereInput!]
    expires?: NexusGenInputs["DateTimeNullableFilter"] | null; // DateTimeNullableFilter
    id: NexusGenInputs["StringFilter"]; // StringFilter!
    sessionToken?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    user?: NexusGenInputs["UserRelationFilter"] | null; // UserRelationFilter
    userId?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
  };
  StringFilter: {
    // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums["QueryModeEnum"] | null; // QueryModeEnum
    not?: NexusGenInputs["NestedStringFilter"] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    search?: string | null; // String
    startsWith?: string | null; // String
  };
  StringNullableFilter: {
    // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums["QueryModeEnum"] | null; // QueryModeEnum
    not?: NexusGenInputs["NestedStringNullableFilter"] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    search?: string | null; // String
    startsWith?: string | null; // String
  };
  StringNullableListFilter: {
    // input type
    equals?: string[] | null; // [String!]
    has?: string | null; // String
    hasEvery?: string[] | null; // [String!]
    hasSome?: string[] | null; // [String!]
    isEmpty?: boolean | null; // Boolean
  };
  UserOrderByRelevanceInput: {
    // input type
    fields: NexusGenEnums["UserOrderByRelevanceFieldEnum"][]; // [UserOrderByRelevanceFieldEnum!]!
    search: string; // String!
    sort: NexusGenEnums["SortOrderEnum"]; // SortOrderEnum!
  };
  UserOrderByWithRelationAndSearchRelevanceInput: {
    // input type
    _relevance?: NexusGenInputs["UserOrderByRelevanceInput"] | null; // UserOrderByRelevanceInput
    accounts?: NexusGenInputs["AccountOrderByRelationAggregateInput"] | null; // AccountOrderByRelationAggregateInput
    comments?: NexusGenInputs["CommentOrderByRelationAggregateInput"] | null; // CommentOrderByRelationAggregateInput
    createdAt?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    email?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    emailVerified?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    entries?: NexusGenInputs["EntryOrderByRelationAggregateInput"] | null; // EntryOrderByRelationAggregateInput
    id?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    image?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    name?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    profile?:
      | NexusGenInputs["ProfileOrderByWithRelationAndSearchRelevanceInput"]
      | null; // ProfileOrderByWithRelationAndSearchRelevanceInput
    role?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    sessions?: NexusGenInputs["SessionOrderByRelationAggregateInput"] | null; // SessionOrderByRelationAggregateInput
    status?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    updatedAt?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  UserOrderByWithRelationInput: {
    // input type
    UserOrderByWithRelationInput?: Array<
      NexusGenInputs["UserOrderByWithRelationInput"] | null
    > | null; // [UserOrderByWithRelationInput]
    accounts?: NexusGenInputs["AccountOrderByRelationAggregateInput"] | null; // AccountOrderByRelationAggregateInput
    comments?: NexusGenInputs["CommentOrderByRelationAggregateInput"] | null; // CommentOrderByRelationAggregateInput
    createdAt?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    email?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    emailVerified?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    entries?: NexusGenInputs["EntryOrderByRelationAggregateInput"] | null; // EntryOrderByRelationAggregateInput
    id?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    image?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    name?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    profile?: NexusGenInputs["ProfileOrderByWithRelationInput"] | null; // ProfileOrderByWithRelationInput
    role?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    sessions?: NexusGenInputs["SessionOrderByRelationAggregateInput"] | null; // SessionOrderByRelationAggregateInput
    status?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
    updatedAt?: NexusGenEnums["SortOrderEnum"] | null; // SortOrderEnum
  };
  UserRelationFilter: {
    // input type
    is?: NexusGenInputs["UserWhereInput"] | null; // UserWhereInput
    isNot?: NexusGenInputs["UserWhereInput"] | null; // UserWhereInput
  };
  UserWhereInput: {
    // input type
    AND?: NexusGenInputs["UserWhereInput"][] | null; // [UserWhereInput!]
    NOT?: NexusGenInputs["UserWhereInput"][] | null; // [UserWhereInput!]
    OR?: NexusGenInputs["UserWhereInput"][] | null; // [UserWhereInput!]
    accounts?: NexusGenInputs["AccountListRelationFilter"] | null; // AccountListRelationFilter
    comments?: NexusGenInputs["CommentListRelationFilter"] | null; // CommentListRelationFilter
    createdAt?: NexusGenInputs["DateTimeFilter"] | null; // DateTimeFilter
    email?: NexusGenInputs["StringFilter"] | null; // StringFilter
    emailVerified?: NexusGenInputs["DateTimeNullableFilter"] | null; // DateTimeNullableFilter
    entries?: NexusGenInputs["EntryListRelationFilter"] | null; // EntryListRelationFilter
    id?: NexusGenInputs["StringFilter"] | null; // StringFilter
    image?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    imageMeta?: NexusGenInputs["MediaItemRelationFilter"] | null; // MediaItemRelationFilter
    name?: NexusGenInputs["StringNullableFilter"] | null; // StringNullableFilter
    profile?: NexusGenInputs["ProfileRelationFilter"] | null; // ProfileRelationFilter
    role?: NexusGenInputs["EnumRoleNullableFilter"] | null; // EnumRoleNullableFilter
    sessions?: NexusGenInputs["SessionListRelationFilter"] | null; // SessionListRelationFilter
    status?: NexusGenInputs["EnumUserStatusNullableFilter"] | null; // EnumUserStatusNullableFilter
    updatedAt?: NexusGenInputs["DateTimeNullableFilter"] | null; // DateTimeNullableFilter
  };
  UserWhereUniqueInput: {
    // input type
    email?: string | null; // String
    id?: string | null; // String
  };
}

export interface NexusGenEnums {
  Gender: Prisma.Gender;
  MediaItemDestination: Prisma.MediaItemDestination;
  MimeType: Prisma.MimeType;
  ProfileOrderByRelevanceFieldEnum:
    | "activiyFeed"
    | "bio"
    | "city"
    | "country"
    | "coverPhoto"
    | "dob"
    | "id"
    | "occupation"
    | "phoneNumber"
    | "recentActivity"
    | "userId";
  Pronouns: Prisma.Pronouns;
  QueryModeEnum: "default" | "insensitive";
  Reaction: Prisma.Reaction;
  Role: Prisma.Role;
  SortOrderEnum: "asc" | "desc";
  UserOrderByRelevanceFieldEnum:
    | "email"
    | "firstName"
    | "id"
    | "image"
    | "lastName"
    | "password";
  UserScalarFieldsEnum:
    | "createdAt"
    | "email"
    | "emailVerified"
    | "firstName"
    | "id"
    | "image"
    | "lastName"
    | "password"
    | "role"
    | "status"
    | "updatedAt";
  UserStatus: Prisma.UserStatus;
}

export interface NexusGenScalars {
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  Date: string;
  DateTime: object;
  Json: string;
  PhoneNumber: string;
  Time: string;
  UUID: string;
  Upload: object;
}

export interface NexusGenObjects {
  Account: Prisma.Account;
  AccountEdge: {
    // root type
    cursor: string; // String!
    node?: NexusGenRootTypes["Account"] | null; // Account
  };
  Bio: Prisma.Bio;
  Category: Prisma.Category;
  Comment: Prisma.Comment;
  CommentEdge: {
    // root type
    cursor: string; // String!
    node?: NexusGenRootTypes["Comment"] | null; // Comment
  };
  Entry: Prisma.Entry;
  EntryComments_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["CommentEdge"] | null> | null; // [CommentEdge]
    nodes?: Array<NexusGenRootTypes["Comment"] | null> | null; // [Comment]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  EntryCount: {
    // root type
    comments: number; // Int!
  };
  EntryEdge: {
    // root type
    cursor: string; // String!
    node?: NexusGenRootTypes["Entry"] | null; // Entry
  };
  MediaItem: Prisma.MediaItem;
  Mutation: {};
  PageInfo: {
    // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  };
  Profile: Prisma.Profile;
  ProfileEdge: {
    // root type
    cursor: string; // String!
    node?: NexusGenRootTypes["Profile"] | null; // Profile
  };
  Query: {};
  QueryAccounts_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["AccountEdge"] | null> | null; // [AccountEdge]
    nodes?: Array<NexusGenRootTypes["Account"] | null> | null; // [Account]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryAllAccounts_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["AccountEdge"] | null> | null; // [AccountEdge]
    nodes?: Array<NexusGenRootTypes["Account"] | null> | null; // [Account]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryAllEntries_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes?: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryEntries_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes?: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryEntryFeed_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes?: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryFilterUsers_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["UserEdge"] | null> | null; // [UserEdge]
    nodes?: Array<NexusGenRootTypes["User"] | null> | null; // [User]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryGetAllEntries_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes?: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryGetUserByAccount_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["AccountEdge"] | null> | null; // [AccountEdge]
    nodes?: Array<NexusGenRootTypes["Account"] | null> | null; // [Account]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryListProfiles_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["ProfileEdge"] | null> | null; // [ProfileEdge]
    nodes?: Array<NexusGenRootTypes["Profile"] | null> | null; // [Profile]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryListSessions_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["SessionEdge"] | null> | null; // [SessionEdge]
    nodes?: Array<NexusGenRootTypes["Session"] | null> | null; // [Session]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QuerySearchByUserEmail_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["UserEdge"] | null> | null; // [UserEdge]
    nodes?: Array<NexusGenRootTypes["User"] | null> | null; // [User]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QuerySearchEntriesByTitle_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes?: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QuerySession_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["SessionEdge"] | null> | null; // [SessionEdge]
    nodes?: Array<NexusGenRootTypes["Session"] | null> | null; // [Session]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryUserAccount_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["AccountEdge"] | null> | null; // [AccountEdge]
    nodes?: Array<NexusGenRootTypes["Account"] | null> | null; // [Account]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryUserEntries_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes?: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryUsersQuery_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["UserEdge"] | null> | null; // [UserEdge]
    nodes?: Array<NexusGenRootTypes["User"] | null> | null; // [User]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  QueryVerificationTokens_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["VerificationTokenEdge"] | null> | null; // [VerificationTokenEdge]
    nodes?: Array<NexusGenRootTypes["VerificationToken"] | null> | null; // [VerificationToken]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  Session: Prisma.Session;
  SessionEdge: {
    // root type
    cursor: string; // String!
    node?: NexusGenRootTypes["Session"] | null; // Session
  };
  User: Prisma.User;
  UserAccounts_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["AccountEdge"] | null> | null; // [AccountEdge]
    nodes?: Array<NexusGenRootTypes["Account"] | null> | null; // [Account]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  UserComments_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["CommentEdge"] | null> | null; // [CommentEdge]
    nodes?: Array<NexusGenRootTypes["Comment"] | null> | null; // [Comment]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  UserCount: {
    // root type
    accounts: number; // Int!
    comments: number; // Int!
    entries: number; // Int!
    sessions: number; // Int!
  };
  UserEdge: {
    // root type
    cursor: string; // String!
    node?: NexusGenRootTypes["User"] | null; // User
  };
  UserEntries_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes?: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  UserSessions_Connection: {
    // root type
    edges?: Array<NexusGenRootTypes["SessionEdge"] | null> | null; // [SessionEdge]
    nodes?: Array<NexusGenRootTypes["Session"] | null> | null; // [Session]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
  };
  VerificationToken: Prisma.VerificationToken;
  VerificationTokenEdge: {
    // root type
    cursor: string; // String!
    node?: NexusGenRootTypes["VerificationToken"] | null; // VerificationToken
  };
}

export interface NexusGenInterfaces {
  Node:
    | core.Discriminate<"Account", "required">
    | core.Discriminate<"Comment", "required">
    | core.Discriminate<"Entry", "required">
    | core.Discriminate<"Profile", "required">
    | core.Discriminate<"Session", "required">
    | core.Discriminate<"User", "required">
    | core.Discriminate<"VerificationToken", "required">;
}

export interface NexusGenUnions {}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects;

export type NexusGenAllTypes = NexusGenRootTypes &
  NexusGenScalars &
  NexusGenEnums;

export interface NexusGenFieldTypes {
  Account: {
    // field return type
    access_token: string | null; // String
    expires_at: number | null; // Int
    id: string; // String!
    id_token: string | null; // String
    oauth_token: string | null; // String
    oauth_token_secret: string | null; // String
    provider: string | null; // String
    providerAccountId: string | null; // String
    refresh_token: string | null; // String
    scope: string | null; // String
    session_state: string | null; // String
    token_type: string | null; // String
    type: string | null; // String
    user: NexusGenRootTypes["User"] | null; // User
    userId: string | null; // String
  };
  AccountEdge: {
    // field return type
    cursor: string; // String!
    node: NexusGenRootTypes["Account"] | null; // Account
  };
  Bio: {
    // field return type
    body: string | null; // String
    createdAt: NexusGenScalars["DateTime"] | null; // DateTime
    headline: string | null; // String
    intro: string | null; // String
    status: string | null; // String
    updatedAt: NexusGenScalars["DateTime"] | null; // DateTime
  };
  Category: {
    // field return type
    createdAt: NexusGenScalars["DateTime"] | null; // DateTime
    creatorId: string | null; // String
    name: string | null; // String
    root: boolean | null; // Boolean
    updatedAt: NexusGenScalars["DateTime"] | null; // DateTime
  };
  Comment: {
    // field return type
    attachment: NexusGenRootTypes["MediaItem"] | null; // MediaItem
    author: NexusGenRootTypes["User"] | null; // User
    authorId: string | null; // String
    body: string | null; // String
    createdAt: NexusGenScalars["DateTime"]; // DateTime!
    entry: NexusGenRootTypes["Entry"] | null; // Entry
    entryId: string | null; // String
    id: string; // String!
    position: string | null; // String
    reactions: Array<NexusGenEnums["Reaction"] | null> | null; // [Reaction]
    updatedAt: NexusGenScalars["DateTime"] | null; // DateTime
  };
  CommentEdge: {
    // field return type
    cursor: string; // String!
    node: NexusGenRootTypes["Comment"] | null; // Comment
  };
  Entry: {
    // field return type
    _count: NexusGenRootTypes["EntryCount"]; // EntryCount!
    attachments: Array<NexusGenRootTypes["MediaItem"] | null> | null; // [MediaItem]
    author: NexusGenRootTypes["User"] | null; // User
    authorId: string | null; // String
    categories: Array<NexusGenRootTypes["Category"] | null> | null; // [Category]
    comments: NexusGenRootTypes["EntryComments_Connection"] | null; // EntryComments_Connection
    content: string | null; // String
    createdAt: NexusGenScalars["DateTime"] | null; // DateTime
    featuredImage: NexusGenRootTypes["MediaItem"] | null; // MediaItem
    id: string; // String!
    published: boolean | null; // Boolean
    reactions: Array<NexusGenEnums["Reaction"] | null> | null; // [Reaction]
    title: string | null; // String
    updatedAt: NexusGenScalars["DateTime"] | null; // DateTime
  };
  EntryComments_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["CommentEdge"] | null> | null; // [CommentEdge]
    nodes: Array<NexusGenRootTypes["Comment"] | null> | null; // [Comment]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  EntryCount: {
    // field return type
    comments: number; // Int!
  };
  EntryEdge: {
    // field return type
    cursor: string; // String!
    node: NexusGenRootTypes["Entry"] | null; // Entry
  };
  MediaItem: {
    // field return type
    ariaLabel: string | null; // String
    caption: string | null; // String
    description: string | null; // String
    destination: NexusGenEnums["MediaItemDestination"] | null; // MediaItemDestination
    fileLastModified: NexusGenScalars["DateTime"] | null; // DateTime
    filename: string | null; // String
    filetype: NexusGenEnums["MimeType"] | null; // MimeType
    height: number; // Float!
    id: string | null; // String
    quality: number; // Int!
    size: string | null; // String
    src: string | null; // String
    srcSet: string | null; // String
    title: string | null; // String
    updatedAt: NexusGenScalars["DateTime"] | null; // DateTime
    uploadedAt: NexusGenScalars["DateTime"] | null; // DateTime
    width: number; // Float!
  };
  Mutation: {
    // field return type
    CreateNewUser: NexusGenRootTypes["User"] | null; // User
    DeleteUser: NexusGenRootTypes["User"] | null; // User
    createEntry: NexusGenRootTypes["Entry"] | null; // Entry
    createProfile: NexusGenRootTypes["Profile"] | null; // Profile
  };
  PageInfo: {
    // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  };
  Profile: {
    // field return type
    activityFeed: string | null; // String
    bio: NexusGenRootTypes["Bio"] | null; // Bio
    city: string | null; // String
    country: string | null; // String
    coverPhoto: NexusGenRootTypes["MediaItem"] | null; // MediaItem
    dob: NexusGenScalars["Date"] | null; // Date
    gender: NexusGenEnums["Gender"] | null; // Gender
    id: string; // String!
    lastSeen: NexusGenScalars["DateTime"] | null; // DateTime
    memberSince: NexusGenScalars["DateTime"] | null; // DateTime
    occupation: string | null; // String
    phoneNumber: NexusGenScalars["PhoneNumber"] | null; // PhoneNumber
    pronouns: NexusGenEnums["Pronouns"] | null; // Pronouns
    recentActivity: string | null; // String
    user: NexusGenRootTypes["User"] | null; // User
    userId: string | null; // String
  };
  ProfileEdge: {
    // field return type
    cursor: string; // String!
    node: NexusGenRootTypes["Profile"] | null; // Profile
  };
  Query: {
    // field return type
    FilterUsers: NexusGenRootTypes["QueryFilterUsers_Connection"] | null; // QueryFilterUsers_Connection
    GetAllEntries: NexusGenRootTypes["QueryGetAllEntries_Connection"] | null; // QueryGetAllEntries_Connection
    GetEntry: NexusGenRootTypes["Entry"] | null; // Entry
    GetSession: NexusGenRootTypes["Session"] | null; // Session
    SearchByUserEmail:
      | NexusGenRootTypes["QuerySearchByUserEmail_Connection"]
      | null; // QuerySearchByUserEmail_Connection
    SearchEntriesByTitle:
      | NexusGenRootTypes["QuerySearchEntriesByTitle_Connection"]
      | null; // QuerySearchEntriesByTitle_Connection
    accounts: NexusGenRootTypes["QueryAccounts_Connection"] | null; // QueryAccounts_Connection
    allAccounts: NexusGenRootTypes["QueryAllAccounts_Connection"] | null; // QueryAllAccounts_Connection
    allEntries: NexusGenRootTypes["QueryAllEntries_Connection"] | null; // QueryAllEntries_Connection
    entries: NexusGenRootTypes["QueryEntries_Connection"] | null; // QueryEntries_Connection
    entryFeed: NexusGenRootTypes["QueryEntryFeed_Connection"] | null; // QueryEntryFeed_Connection
    getUserByAccount:
      | NexusGenRootTypes["QueryGetUserByAccount_Connection"]
      | null; // QueryGetUserByAccount_Connection
    listProfiles: NexusGenRootTypes["QueryListProfiles_Connection"] | null; // QueryListProfiles_Connection
    listSessions: NexusGenRootTypes["QueryListSessions_Connection"] | null; // QueryListSessions_Connection
    node: NexusGenRootTypes["Node"] | null; // Node
    session: NexusGenRootTypes["QuerySession_Connection"] | null; // QuerySession_Connection
    userAccount: NexusGenRootTypes["QueryUserAccount_Connection"] | null; // QueryUserAccount_Connection
    userByEmail: NexusGenRootTypes["User"] | null; // User
    userById: NexusGenRootTypes["User"] | null; // User
    userEntries: NexusGenRootTypes["QueryUserEntries_Connection"] | null; // QueryUserEntries_Connection
    usersQuery: NexusGenRootTypes["QueryUsersQuery_Connection"] | null; // QueryUsersQuery_Connection
    verificationTokens:
      | NexusGenRootTypes["QueryVerificationTokens_Connection"]
      | null; // QueryVerificationTokens_Connection
  };
  QueryAccounts_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["AccountEdge"] | null> | null; // [AccountEdge]
    nodes: Array<NexusGenRootTypes["Account"] | null> | null; // [Account]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryAllAccounts_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["AccountEdge"] | null> | null; // [AccountEdge]
    nodes: Array<NexusGenRootTypes["Account"] | null> | null; // [Account]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryAllEntries_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryEntries_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryEntryFeed_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryFilterUsers_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["UserEdge"] | null> | null; // [UserEdge]
    nodes: Array<NexusGenRootTypes["User"] | null> | null; // [User]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryGetAllEntries_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryGetUserByAccount_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["AccountEdge"] | null> | null; // [AccountEdge]
    nodes: Array<NexusGenRootTypes["Account"] | null> | null; // [Account]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryListProfiles_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["ProfileEdge"] | null> | null; // [ProfileEdge]
    nodes: Array<NexusGenRootTypes["Profile"] | null> | null; // [Profile]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryListSessions_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["SessionEdge"] | null> | null; // [SessionEdge]
    nodes: Array<NexusGenRootTypes["Session"] | null> | null; // [Session]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QuerySearchByUserEmail_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["UserEdge"] | null> | null; // [UserEdge]
    nodes: Array<NexusGenRootTypes["User"] | null> | null; // [User]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QuerySearchEntriesByTitle_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QuerySession_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["SessionEdge"] | null> | null; // [SessionEdge]
    nodes: Array<NexusGenRootTypes["Session"] | null> | null; // [Session]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryUserAccount_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["AccountEdge"] | null> | null; // [AccountEdge]
    nodes: Array<NexusGenRootTypes["Account"] | null> | null; // [Account]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryUserEntries_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryUsersQuery_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["UserEdge"] | null> | null; // [UserEdge]
    nodes: Array<NexusGenRootTypes["User"] | null> | null; // [User]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  QueryVerificationTokens_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["VerificationTokenEdge"] | null> | null; // [VerificationTokenEdge]
    nodes: Array<NexusGenRootTypes["VerificationToken"] | null> | null; // [VerificationToken]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  Session: {
    // field return type
    expires: NexusGenScalars["DateTime"] | null; // DateTime
    id: string; // String!
    sessionToken: string | null; // String
    user: NexusGenRootTypes["User"] | null; // User
    userId: string | null; // String
  };
  SessionEdge: {
    // field return type
    cursor: string; // String!
    node: NexusGenRootTypes["Session"] | null; // Session
  };
  User: {
    // field return type
    _count: NexusGenRootTypes["UserCount"]; // UserCount!
    accounts: NexusGenRootTypes["UserAccounts_Connection"] | null; // UserAccounts_Connection
    comments: NexusGenRootTypes["UserComments_Connection"] | null; // UserComments_Connection
    email: string | null; // String
    emailVerified: NexusGenScalars["DateTime"] | null; // DateTime
    entries: NexusGenRootTypes["UserEntries_Connection"] | null; // UserEntries_Connection
    id: string; // String!
    image: string | null; // String
    imageMeta: NexusGenRootTypes["MediaItem"] | null; // MediaItem
    name: string | null; // String
    profile: NexusGenRootTypes["Profile"] | null; // Profile
    role: NexusGenEnums["Role"] | null; // Role
    sessions: NexusGenRootTypes["UserSessions_Connection"] | null; // UserSessions_Connection
    status: NexusGenEnums["UserStatus"] | null; // UserStatus
  };
  UserAccounts_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["AccountEdge"] | null> | null; // [AccountEdge]
    nodes: Array<NexusGenRootTypes["Account"] | null> | null; // [Account]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  UserComments_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["CommentEdge"] | null> | null; // [CommentEdge]
    nodes: Array<NexusGenRootTypes["Comment"] | null> | null; // [Comment]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  UserCount: {
    // field return type
    accounts: number; // Int!
    comments: number; // Int!
    entries: number; // Int!
    sessions: number; // Int!
  };
  UserEdge: {
    // field return type
    cursor: string; // String!
    node: NexusGenRootTypes["User"] | null; // User
  };
  UserEntries_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["EntryEdge"] | null> | null; // [EntryEdge]
    nodes: Array<NexusGenRootTypes["Entry"] | null> | null; // [Entry]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  UserSessions_Connection: {
    // field return type
    edges: Array<NexusGenRootTypes["SessionEdge"] | null> | null; // [SessionEdge]
    nodes: Array<NexusGenRootTypes["Session"] | null> | null; // [Session]
    pageInfo: NexusGenRootTypes["PageInfo"]; // PageInfo!
    totalCount: number; // Int!
  };
  VerificationToken: {
    // field return type
    expires: NexusGenScalars["DateTime"] | null; // DateTime
    id: string; // String!
    identifier: string | null; // String
    token: string | null; // String
  };
  VerificationTokenEdge: {
    // field return type
    cursor: string; // String!
    node: NexusGenRootTypes["VerificationToken"] | null; // VerificationToken
  };
  Node: {
    // field return type
    id: string; // String!
  };
}

export interface NexusGenFieldTypeNames {
  Account: {
    // field return type name
    access_token: "String";
    expires_at: "Int";
    id: "String";
    id_token: "String";
    oauth_token: "String";
    oauth_token_secret: "String";
    provider: "String";
    providerAccountId: "String";
    refresh_token: "String";
    scope: "String";
    session_state: "String";
    token_type: "String";
    type: "String";
    user: "User";
    userId: "String";
  };
  AccountEdge: {
    // field return type name
    cursor: "String";
    node: "Account";
  };
  Bio: {
    // field return type name
    body: "String";
    createdAt: "DateTime";
    headline: "String";
    intro: "String";
    status: "String";
    updatedAt: "DateTime";
  };
  Category: {
    // field return type name
    createdAt: "DateTime";
    creatorId: "String";
    name: "String";
    root: "Boolean";
    updatedAt: "DateTime";
  };
  Comment: {
    // field return type name
    attachment: "MediaItem";
    author: "User";
    authorId: "String";
    body: "String";
    createdAt: "DateTime";
    entry: "Entry";
    entryId: "String";
    id: "String";
    position: "String";
    reactions: "Reaction";
    updatedAt: "DateTime";
  };
  CommentEdge: {
    // field return type name
    cursor: "String";
    node: "Comment";
  };
  Entry: {
    // field return type name
    _count: "EntryCount";
    attachments: "MediaItem";
    author: "User";
    authorId: "String";
    categories: "Category";
    comments: "EntryComments_Connection";
    content: "String";
    createdAt: "DateTime";
    featuredImage: "MediaItem";
    id: "String";
    published: "Boolean";
    reactions: "Reaction";
    title: "String";
    updatedAt: "DateTime";
  };
  EntryComments_Connection: {
    // field return type name
    edges: "CommentEdge";
    nodes: "Comment";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  EntryCount: {
    // field return type name
    comments: "Int";
  };
  EntryEdge: {
    // field return type name
    cursor: "String";
    node: "Entry";
  };
  MediaItem: {
    // field return type name
    ariaLabel: "String";
    caption: "String";
    description: "String";
    destination: "MediaItemDestination";
    fileLastModified: "DateTime";
    filename: "String";
    filetype: "MimeType";
    height: "Float";
    id: "String";
    quality: "Int";
    size: "String";
    src: "String";
    srcSet: "String";
    title: "String";
    updatedAt: "DateTime";
    uploadedAt: "DateTime";
    width: "Float";
  };
  Mutation: {
    // field return type name
    CreateNewUser: "User";
    DeleteUser: "User";
    createEntry: "Entry";
    createProfile: "Profile";
  };
  PageInfo: {
    // field return type name
    endCursor: "String";
    hasNextPage: "Boolean";
    hasPreviousPage: "Boolean";
    startCursor: "String";
  };
  Profile: {
    // field return type name
    activityFeed: "String";
    bio: "Bio";
    city: "String";
    country: "String";
    coverPhoto: "MediaItem";
    dob: "Date";
    gender: "Gender";
    id: "String";
    lastSeen: "DateTime";
    memberSince: "DateTime";
    occupation: "String";
    phoneNumber: "PhoneNumber";
    pronouns: "Pronouns";
    recentActivity: "String";
    user: "User";
    userId: "String";
  };
  ProfileEdge: {
    // field return type name
    cursor: "String";
    node: "Profile";
  };
  Query: {
    // field return type name
    FilterUsers: "QueryFilterUsers_Connection";
    GetAllEntries: "QueryGetAllEntries_Connection";
    GetEntry: "Entry";
    GetSession: "Session";
    SearchByUserEmail: "QuerySearchByUserEmail_Connection";
    SearchEntriesByTitle: "QuerySearchEntriesByTitle_Connection";
    accounts: "QueryAccounts_Connection";
    allAccounts: "QueryAllAccounts_Connection";
    allEntries: "QueryAllEntries_Connection";
    entries: "QueryEntries_Connection";
    entryFeed: "QueryEntryFeed_Connection";
    getUserByAccount: "QueryGetUserByAccount_Connection";
    listProfiles: "QueryListProfiles_Connection";
    listSessions: "QueryListSessions_Connection";
    node: "Node";
    session: "QuerySession_Connection";
    userAccount: "QueryUserAccount_Connection";
    userByEmail: "User";
    userById: "User";
    userEntries: "QueryUserEntries_Connection";
    usersQuery: "QueryUsersQuery_Connection";
    verificationTokens: "QueryVerificationTokens_Connection";
  };
  QueryAccounts_Connection: {
    // field return type name
    edges: "AccountEdge";
    nodes: "Account";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryAllAccounts_Connection: {
    // field return type name
    edges: "AccountEdge";
    nodes: "Account";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryAllEntries_Connection: {
    // field return type name
    edges: "EntryEdge";
    nodes: "Entry";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryEntries_Connection: {
    // field return type name
    edges: "EntryEdge";
    nodes: "Entry";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryEntryFeed_Connection: {
    // field return type name
    edges: "EntryEdge";
    nodes: "Entry";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryFilterUsers_Connection: {
    // field return type name
    edges: "UserEdge";
    nodes: "User";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryGetAllEntries_Connection: {
    // field return type name
    edges: "EntryEdge";
    nodes: "Entry";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryGetUserByAccount_Connection: {
    // field return type name
    edges: "AccountEdge";
    nodes: "Account";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryListProfiles_Connection: {
    // field return type name
    edges: "ProfileEdge";
    nodes: "Profile";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryListSessions_Connection: {
    // field return type name
    edges: "SessionEdge";
    nodes: "Session";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QuerySearchByUserEmail_Connection: {
    // field return type name
    edges: "UserEdge";
    nodes: "User";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QuerySearchEntriesByTitle_Connection: {
    // field return type name
    edges: "EntryEdge";
    nodes: "Entry";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QuerySession_Connection: {
    // field return type name
    edges: "SessionEdge";
    nodes: "Session";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryUserAccount_Connection: {
    // field return type name
    edges: "AccountEdge";
    nodes: "Account";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryUserEntries_Connection: {
    // field return type name
    edges: "EntryEdge";
    nodes: "Entry";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryUsersQuery_Connection: {
    // field return type name
    edges: "UserEdge";
    nodes: "User";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  QueryVerificationTokens_Connection: {
    // field return type name
    edges: "VerificationTokenEdge";
    nodes: "VerificationToken";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  Session: {
    // field return type name
    expires: "DateTime";
    id: "String";
    sessionToken: "String";
    user: "User";
    userId: "String";
  };
  SessionEdge: {
    // field return type name
    cursor: "String";
    node: "Session";
  };
  User: {
    // field return type name
    _count: "UserCount";
    accounts: "UserAccounts_Connection";
    comments: "UserComments_Connection";
    email: "String";
    emailVerified: "DateTime";
    entries: "UserEntries_Connection";
    id: "String";
    image: "String";
    imageMeta: "MediaItem";
    name: "String";
    profile: "Profile";
    role: "Role";
    sessions: "UserSessions_Connection";
    status: "UserStatus";
  };
  UserAccounts_Connection: {
    // field return type name
    edges: "AccountEdge";
    nodes: "Account";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  UserComments_Connection: {
    // field return type name
    edges: "CommentEdge";
    nodes: "Comment";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  UserCount: {
    // field return type name
    accounts: "Int";
    comments: "Int";
    entries: "Int";
    sessions: "Int";
  };
  UserEdge: {
    // field return type name
    cursor: "String";
    node: "User";
  };
  UserEntries_Connection: {
    // field return type name
    edges: "EntryEdge";
    nodes: "Entry";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  UserSessions_Connection: {
    // field return type name
    edges: "SessionEdge";
    nodes: "Session";
    pageInfo: "PageInfo";
    totalCount: "Int";
  };
  VerificationToken: {
    // field return type name
    expires: "DateTime";
    id: "String";
    identifier: "String";
    token: "String";
  };
  VerificationTokenEdge: {
    // field return type name
    cursor: "String";
    node: "VerificationToken";
  };
  Node: {
    // field return type name
    id: "String";
  };
}

export interface NexusGenArgTypes {
  Entry: {
    comments: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      searchString: string; // String!
      take?: number | null; // Int
    };
  };
  Mutation: {
    CreateNewUser: {
      // args
      email: string; // String!
      expires: NexusGenScalars["Date"]; // Date!
      image?: string | null; // String
      name?: string | null; // String
      sessionToken: string; // String!
    };
    DeleteUser: {
      // args
      id: string; // String!
    };
    createEntry: {
      // args
      content?: string | null; // String
      featuredImage?: string | null; // String
      publish?: boolean | null; // Boolean
      title?: string | null; // String
      userId?: string | null; // String
    };
    createProfile: {
      // args
      dob?: string | null; // String
      email: string; // String!
      phoneNumber?: string | null; // String
      userId?: string | null; // String
    };
  };
  Query: {
    FilterUsers: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      searchString: string; // String!
    };
    GetAllEntries: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      searchString: string; // String!
      take?: number | null; // Int
    };
    GetEntry: {
      // args
      id: string; // String!
    };
    GetSession: {
      // args
      id: string; // String!
    };
    SearchByUserEmail: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      search: string; // String!
    };
    SearchEntriesByTitle: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      searchString: string; // String!
    };
    accounts: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      userId: string; // String!
    };
    allAccounts: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      take: number | null; // Int
    };
    allEntries: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      take: number; // Int!
    };
    entries: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    };
    entryFeed: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      searchString?: string | null; // String
      skip?: number | null; // Int
      take: number | null; // Int
    };
    getUserByAccount: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      id: string; // String!
      last?: number | null; // Int
      provider: string; // String!
      providerAccountId: string; // String!
    };
    listProfiles: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy: NexusGenEnums["SortOrderEnum"]; // SortOrderEnum!
    };
    listSessions: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy: NexusGenInputs["SessionOrderBy"]; // SessionOrderBy!
    };
    node: {
      // args
      id: string; // String!
    };
    session: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    };
    userAccount: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    };
    userByEmail: {
      // args
      email: string; // String!
    };
    userById: {
      // args
      id: string; // String!
    };
    userEntries: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      id?: string | null; // String
      last?: number | null; // Int
    };
    usersQuery: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    };
    verificationTokens: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    };
  };
  User: {
    accounts: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    };
    comments: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    };
    entries: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    };
    sessions: {
      // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    };
  };
}

export interface NexusGenAbstractTypeMembers {
  Node:
    | "Account"
    | "Comment"
    | "Entry"
    | "Profile"
    | "Session"
    | "User"
    | "VerificationToken";
}

export interface NexusGenTypeInterfaces {
  Account: "Node";
  Comment: "Node";
  Entry: "Node";
  Profile: "Node";
  Session: "Node";
  User: "Node";
  VerificationToken: "Node";
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false;
    __typename: true;
    resolveType: true;
  };
};

export interface NexusGenTypes {
  context: ctx;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes:
    | NexusGenTypes["inputNames"]
    | NexusGenTypes["enumNames"]
    | NexusGenTypes["scalarNames"];
  allOutputTypes:
    | NexusGenTypes["objectNames"]
    | NexusGenTypes["enumNames"]
    | NexusGenTypes["unionNames"]
    | NexusGenTypes["interfaceNames"]
    | NexusGenTypes["scalarNames"];
  allNamedTypes:
    | NexusGenTypes["allInputTypes"]
    | NexusGenTypes["allOutputTypes"];
  abstractTypes: NexusGenTypes["interfaceNames"] | NexusGenTypes["unionNames"];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {
    /**
     * The complexity for an individual field. Return a number
     * or a function that returns a number to specify the
     * complexity for this field.
     */
    complexity?: QueryComplexity<TypeName, FieldName>;
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean;
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[];
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean;
  }
  interface NexusGenPluginInputFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean;
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[];
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean;
  }
  interface NexusGenPluginSchemaConfig {}
  interface NexusGenPluginArgConfig {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean;
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[];
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean;
  }
}
