export type RoleType = keyof typeof Role;

export enum SortOrder {
  asc = "asc",
  desc = "desc"
}

export enum QueryMode {
  default = "default",
  insensitive = "insensitive"
}

export type UserStatusType = keyof typeof UserStatus;
export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
  UNCERTAIN = "UNCERTAIN",
  OTHER = "OTHER"
}

export enum Pronouns {
  SHE_HER_HERS = "SHE_HER_HERS",
  HE_HIM_HIS = "HE_HIM_HIS",
  THEY_THEM_THEIRS = "THEY_THEM_THEIRS",
  NOT_LISTED = "NOT_LISTED",
  PREFER_NOT_TO_SAY = "PREFER_NOT_TO_SAY"
}

export enum Role {
  SUPERADMIN = "SUPERADMIN",
  ADMIN = "ADMIN",
  MAINTAINER = "MAINTAINER",
  USER = "USER"
}

export enum MediaItemDestination {
  COVER_IMAGE = "COVER_IMAGE",
  AVATAR = "AVATAR",
  COMMENT_ATTACHMENT = "COMMENT_ATTACHMENT",
  ENTRY_ATTACHMENT = "ENTRY_ATTACHMENT",
  FEATURED_IMAGE = "FEATURED_IMAGE"
}

export enum Reaction {
  LIKE = "LIKE",
  LOVE = "LOVE",
  LAUGH = "LAUGH",
  TEARS = "TEARS",
  DISLIKE = "DISLIKE",
  ANGRY = "ANGRY",
  CONFUSED = "CONFUSED",
  CARE = "CARE",
  WOW = "WOW",
  PARROT = "PARROT",
  ROCKET = "ROCKET"
}

export enum UserStatus {
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",
  SUSPENDED = "SUSPENDED",
  DELETED = "DELETED",
  BANNED = "BANNED",
  DEACTIVATED = "DEACTIVATED"
}

export enum Country {
  Afghanistan = "AF",
  AlandIslands = "AX",
  Albania = "AL",
  Algeria = "DZ",
  AmericanSamoa = "AS",
  Andorra = "AD",
  Angola = "AO",
  Anguilla = "AI",
  Antarctica = "AQ",
  AntiguaAndBarbuda = "AG",
  Argentina = "AR",
  Armenia = "AM",
  Aruba = "AW",
  Australia = "AU",
  Austria = "AT",
  Azerbaijan = "AZ",
  Bahamas = "BS",
  Bahrain = "BH",
  Bangladesh = "BD",
  Barbados = "BB",
  Belarus = "BY",
  Belgium = "BE",
  Belize = "BZ",
  Benin = "BJ",
  Bermuda = "BM",
  Bhutan = "BT",
  Bolivia = "BO",
  BonaireSintEustatiusSaba = "BQ",
  BosniaAndHerzegovina = "BA",
  Botswana = "BW",
  BouvetIsland = "BV",
  Brazil = "BR",
  BritishIndianOceanTerritory = "IO",
  BruneiDarussalam = "BN",
  Bulgaria = "BG",
  BurkinaFaso = "BF",
  Burundi = "BI",
  Cambodia = "KH",
  Cameroon = "CM",
  Canada = "CA",
  CapeVerde = "CV",
  CaymanIslands = "KY",
  CentralAfricanRepublic = "CF",
  Chad = "TD",
  Chile = "CL",
  China = "CN",
  ChristmasIsland = "CX",
  CocosKeelingIslands = "CC",
  Colombia = "CO",
  Comoros = "KM",
  Congo = "CG",
  CongoDemocraticRepublic = "CD",
  CookIslands = "CK",
  CostaRica = "CR",
  CoteDIvoire = "CI",
  Croatia = "HR",
  Cuba = "CU",
  Curaçao = "CW",
  Cyprus = "CY",
  CzechRepublic = "CZ",
  Denmark = "DK",
  Djibouti = "DJ",
  Dominica = "DM",
  DominicanRepublic = "DO",
  Ecuador = "EC",
  Egypt = "EG",
  ElSalvador = "SV",
  EquatorialGuinea = "GQ",
  Eritrea = "ER",
  Estonia = "EE",
  Ethiopia = "ET",
  FalklandIslands = "FK",
  FaroeIslands = "FO",
  Fiji = "FJ",
  Finland = "FI",
  France = "FR",
  FrenchGuiana = "GF",
  FrenchPolynesia = "PF",
  FrenchSouthernTerritories = "TF",
  Gabon = "GA",
  Gambia = "GM",
  Georgia = "GE",
  Germany = "DE",
  Ghana = "GH",
  Gibraltar = "GI",
  Greece = "GR",
  Greenland = "GL",
  Grenada = "GD",
  Guadeloupe = "GP",
  Guam = "GU",
  Guatemala = "GT",
  Guernsey = "GG",
  Guinea = "GN",
  GuineaBissau = "GW",
  Guyana = "GY",
  Haiti = "HT",
  HeardIslandMcdonaldIslands = "HM",
  HolySeeVaticanCityState = "VA",
  Honduras = "HN",
  HongKong = "HK",
  Hungary = "HU",
  Iceland = "IS",
  India = "IN",
  Indonesia = "ID",
  Iran = "IR",
  Iraq = "IQ",
  Ireland = "IE",
  IsleOfMan = "IM",
  Israel = "IL",
  Italy = "IT",
  Jamaica = "JM",
  Japan = "JP",
  Jersey = "JE",
  Jordan = "JO",
  Kazakhstan = "KZ",
  Kenya = "KE",
  Kiribati = "KI",
  Korea = "KR",
  KoreaDemocraticPeoplesRepublic = "KP",
  Kuwait = "KW",
  Kyrgyzstan = "KG",
  LaoPeoplesDemocraticRepublic = "LA",
  Latvia = "LV",
  Lebanon = "LB",
  Lesotho = "LS",
  Liberia = "LR",
  LibyanArabJamahiriya = "LY",
  Liechtenstein = "LI",
  Lithuania = "LT",
  Luxembourg = "LU",
  Macao = "MO",
  Macedonia = "MK",
  Madagascar = "MG",
  Malawi = "MW",
  Malaysia = "MY",
  Maldives = "MV",
  Mali = "ML",
  Malta = "MT",
  MarshallIslands = "MH",
  Martinique = "MQ",
  Mauritania = "MR",
  Mauritius = "MU",
  Mayotte = "YT",
  Mexico = "MX",
  Micronesia = "FM",
  Moldova = "MD",
  Monaco = "MC",
  Mongolia = "MN",
  Montenegro = "ME",
  Montserrat = "MS",
  Morocco = "MA",
  Mozambique = "MZ",
  Myanmar = "MM",
  Namibia = "NA",
  Nauru = "NR",
  Nepal = "NP",
  Netherlands = "NL",
  NewCaledonia = "NC",
  NewZealand = "NZ",
  Nicaragua = "NI",
  Niger = "NE",
  Nigeria = "NG",
  Niue = "NU",
  NorfolkIsland = "NF",
  NorthernMarianaIslands = "MP",
  Norway = "NO",
  Oman = "OM",
  Pakistan = "PK",
  Palau = "PW",
  PalestinianTerritory = "PS",
  Panama = "PA",
  PapuaNewGuinea = "PG",
  Paraguay = "PY",
  Peru = "PE",
  Philippines = "PH",
  Pitcairn = "PN",
  Poland = "PL",
  Portugal = "PT",
  PuertoRico = "PR",
  Qatar = "QA",
  Reunion = "RE",
  Romania = "RO",
  RussianFederation = "RU",
  Rwanda = "RW",
  SaintBarthelemy = "BL",
  SaintHelena = "SH",
  SaintKittsAndNevis = "KN",
  SaintLucia = "LC",
  SaintMartin = "MF",
  SaintPierreAndMiquelon = "PM",
  SaintVincentAndGrenadines = "VC",
  Samoa = "WS",
  SanMarino = "SM",
  SaoTomeAndPrincipe = "ST",
  SaudiArabia = "SA",
  Senegal = "SN",
  Serbia = "RS",
  Seychelles = "SC",
  SierraLeone = "SL",
  Singapore = "SG",
  SintMaarten = "SX",
  Slovakia = "SK",
  Slovenia = "SI",
  SolomonIslands = "SB",
  Somalia = "SO",
  SouthAfrica = "ZA",
  SouthGeorgiaAndSandwichIsl = "GS",
  SouthSudan = "SS",
  Spain = "ES",
  SriLanka = "LK",
  Sudan = "SD",
  Suriname = "SR",
  SvalbardAndJanMayen = "SJ",
  Swaziland = "SZ",
  Sweden = "SE",
  Switzerland = "CH",
  SyrianArabRepublic = "SY",
  Taiwan = "TW",
  Tajikistan = "TJ",
  Tanzania = "TZ",
  Thailand = "TH",
  TimorLeste = "TL",
  Togo = "TG",
  Tokelau = "TK",
  Tonga = "TO",
  TrinidadAndTobago = "TT",
  Tunisia = "TN",
  Turkey = "TR",
  Turkmenistan = "TM",
  TurksAndCaicosIslands = "TC",
  Tuvalu = "TV",
  Uganda = "UG",
  Ukraine = "UA",
  UnitedArabEmirates = "AE",
  UnitedKingdom = "GB",
  UnitedStates = "US",
  UnitedStatesOutlyingIslands = "UM",
  Uruguay = "UY",
  Uzbekistan = "UZ",
  Vanuatu = "VU",
  Venezuela = "VE",
  Vietnam = "VN",
  VirginIslandsBritish = "VG",
  VirginIslandsUS = "VI",
  WallisAndFutuna = "WF",
  WesternSahara = "EH",
  Yemen = "YE",
  Zambia = "ZM",
  Zimbabwe = "ZW"
}

export enum CountryCode {
  UK = 44,
  USA = 1,
  Algeria = 213,
  Andorra = 376,
  Angola = 244,
  Anguilla = 1264,
  AntiguaBarbuda = 1268,
  Argentina = 54,
  Armenia = 374,
  Aruba = 297,
  Australia = 61,
  Austria = 43,
  Azerbaijan = 994,
  Bahamas = 1242,
  Bahrain = 973,
  Bangladesh = 880,
  Barbados = 1246,
  Belarus = 375,
  Belgium = 32,
  Belize = 501,
  Benin = 229,
  Bermuda = 1441,
  Bhutan = 975,
  Bolivia = 591,
  BosniaHerzegovina = 387,
  Botswana = 267,
  Brazil = 55,
  Brunei = 673,
  Bulgaria = 359,
  BurkinaFaso = 226,
  Burundi = 257,
  Cambodia = 855,
  Cameroon = 237,
  Canada = 1,
  CapeVerdeIslands = 238,
  CaymanIslands = 1345,
  CentralAfricanRepublic = 236,
  Chile = 56,
  China = 86,
  Colombia = 57,
  Comoros = 269,
  Congo = 242,
  CookIslands = 682,
  CostaRica = 506,
  Croatia = 385,
  Cuba = 53,
  CyprusNorth = 90392,
  CyprusSouth = 357,
  CzechRepublic = 42,
  Denmark = 45,
  Djibouti = 253,
  Dominica = 1809,
  DominicanRepublic = 1809,
  Ecuador = 593,
  Egypt = 20,
  ElSalvador = 503,
  EquatorialGuinea = 240,
  Eritrea = 291,
  Estonia = 372,
  Ethiopia = 251,
  FalklandIslands = 500,
  FaroeIslands = 298,
  Fiji = 679,
  Finland = 358,
  France = 33,
  FrenchGuiana = 594,
  FrenchPolynesia = 689,
  Gabon = 241,
  Gambia = 220,
  Georgia = 7880,
  Germany = 49,
  Ghana = 233,
  Gibraltar = 350,
  Greece = 30,
  Greenland = 299,
  Grenada = 1473,
  Guadeloupe = 590,
  Guam = 671,
  Guatemala = 502,
  Guinea = 224,
  GuineaBissau = 245,
  Guyana = 592,
  Haiti = 509,
  Honduras = 504,
  HongKong = 852,
  Hungary = 36,
  Iceland = 354,
  India = 91,
  Indonesia = 62,
  Iran = 98,
  Iraq = 964,
  Ireland = 353,
  Israel = 972,
  Italy = 39,
  Jamaica = 1876,
  Japan = 81,
  Jordan = 962,
  Kazakhstan = 7,
  Kenya = 254,
  Kiribati = 686,
  KoreaNorth = 850,
  KoreaSouth = 82,
  Kuwait = 965,
  Kyrgyzstan = 996,
  Laos = 856,
  Latvia = 371,
  Lebanon = 961,
  Lesotho = 266,
  Liberia = 231,
  Libya = 218,
  Liechtenstein = 417,
  Lithuania = 370,
  Luxembourg = 352,
  Macao = 853,
  Macedonia = 389,
  Madagascar = 261,
  Malawi = 265,
  Malaysia = 60,
  Maldives = 960,
  Mali = 223,
  Malta = 356,
  MarshallIslands = 692,
  Martinique = 596,
  Mauritania = 222,
  Mauritius = 230,
  Mayotte = 269,
  Mexico = 52,
  Micronesia = 691,
  Moldova = 373,
  Monaco = 377,
  Mongolia = 976,
  Montserrat = 1664,
  Morocco = 212,
  Mozambique = 258,
  Myanmar = 95,
  Namibia = 264,
  Nauru = 674,
  Nepal = 977,
  Netherlands = 31,
  NewCaledonia = 687,
  NewZealand = 64,
  Nicaragua = 505,
  Niger = 227,
  Nigeria = 234,
  Niue = 683,
  NorfolkIslands = 672,
  NorthernMarianas = 670,
  Norway = 47,
  Oman = 968,
  Palau = 680,
  Panama = 507,
  PapuaNewGuinea = 675,
  Paraguay = 595,
  Peru = 51,
  Philippines = 63,
  Poland = 48,
  Portugal = 351,
  PuertoRico = 1787,
  Qatar = 974,
  Reunion = 262,
  Romania = 40,
  Russia = 7,
  Rwanda = 250,
  SanMarino = 378,
  SaoTomePrincipe = 239,
  SaudiArabia = 966,
  Senegal = 221,
  Serbia = 381,
  Seychelles = 248,
  SierraLeone = 232,
  Singapore = 65,
  SlovakRepublic = 421,
  Slovenia = 386,
  SolomonIslands = 677,
  Somalia = 252,
  SouthAfrica = 27,
  Spain = 34,
  SriLanka = 94,
  StHelena = 290,
  StKitts = 1869,
  StLucia = 1758,
  Sudan = 249,
  Suriname = 597,
  Swaziland = 268,
  Sweden = 46,
  Switzerland = 41,
  Syria = 963,
  Taiwan = 886,
  Tajikstan = 7,
  Thailand = 66,
  Togo = 228,
  Tonga = 676,
  TrinidadTobago = 1868,
  Tunisia = 216,
  Turkey = 90,
  Turkmenistan = 7,
  TurkmenistanB = 993,
  TurksCaicosIslands = 1649,
  Tuvalu = 688,
  Uganda = 256,
  Ukraine = 380,
  UnitedArabEmirates = 971,
  Uruguay = 598,
  Uzbekistan = 7,
  Vanuatu = 678,
  VaticanCity = 379,
  Venezuela = 58,
  Vietnam = 84,
  VirginIslandsBritish = 1284,
  VirginIslandsUS = 1340,
  WallisFutuna = 681,
  YemenNorth = 969,
  YemenSouth = 967,
  Zambia = 260,
  Zimbabwe = 263
}

export enum MimeType {
  GIF = "GIF",
  JPEG = "JPEG",
  WEBP = "WEBP",
  AVIF = "AVIF",
  PNG = "PNG",
  SVG = "SVG",
  TIFF = "TIFF",
  BMP = "BMP"
}

export type MediaItem = {
  mediaItemId: string;
  uploadedAt: Date;
  updatedAt?: Date;
  filename: string;
  size: string;
  filetype: keyof typeof MimeType;
  destination: keyof typeof MediaItemDestination;
  fileLastModified: Date;
  width: number;
  height: number;
  quality: number;
  src: string;
  srcSet: string;
  ariaLabel: string;
  title: string;
  caption: string;
};

export interface SetMediaItem {
  set: MediaItem;
}

export type Bio = {
  headline: string;
  intro?: string;
  body?: string;
  status?: string;
  createdAt: Date;
  updatedAt?: Date;
};

export interface SetBio {
  set: Bio;
}

export type Category = {
  creatorId: string;
  createdAt: Date;
  updatedAt: Date;
  root: boolean;
  name: string;
  entryId?: string;
};

export interface SetCategory {
  set: Category;
}
